### ISSUE TITLE
Get this on stack

### ISSUE THREAD

**Issue by DavidM-D** [ollef/rope-utf16-splay#1]
Any chance I/you can put this on stack? I'm happy to do the legwork if you like, it makes https://github.com/digital-asset/daml IDE build scripts a bit nicer

**Comment by ollef** [comment]
Sure, not a problem. I wasn't aware there were any users. If you'd like to do the legwork, that'd be ideal for me. :) Cheers!

**Comment by DavidM-D** [comment]
Great, do you mind me adding it stackage under your name in https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml? If not I can add it under my own name

**Comment by ollef** [comment]
You can use my name. 🙂
