### ISSUE TITLE
splitAtLine missing

### ISSUE THREAD

**Issue by alanz** [ollef/rope-utf16-splay#2]
We are using this in haskell-ide-engine at https://github.com/haskell/haskell-ide-engine/blob/master/hie-plugin-api/Haskell/Ide/Engine/PluginUtils.hs#L288-L293

**Comment by alanz** [comment]
cc @ndmitchell

**Comment by alanz** [comment]
And it looks like it can be done using some combination of  `span`,  `takeWhile`, `dropWhile`.

**Comment by alanz** [comment]
or feeding the output of `rowColumnCodeUnits` to `splitAt`.

**Comment by ollef** [comment]
Added in [version 0.3.1.0](https://github.com/ollef/rope-utf16-splay/commit/675875d6a0469fc0ce5657f6e144b0af6e8364e2).
